// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import envConfig from "./src/shared/config/env";
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: `mysql://${envConfig.MYSQL_DATABASE_NAME}:${envConfig.MYSQL_DATABASE_PASSWORD}@${envConfig.MYSQL_DATABASE_HOST}:${envConfig.MYSQL_DATABASE_PORT}/${envConfig.MYSQL_DATABASE_NAME}?sslaccept=strict`,
    // shadowDatabaseUrl: envConfig.SHADOW_DATABASE_URL,
  },
});
